name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  performance-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Install Apache Benchmark
        run: sudo apt-get update && sudo apt-get install -y apache2-utils

      - name: Start the application
        run: |
          nohup ./gradlew bootRun > app.log 2>&1 &
          echo "App starting... wait for it to be ready"
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/health; then
              echo "Application is up!"
              break
            fi
            sleep 1
          done

      - name: Run performance test with Apache Benchmark
        run: |
          echo "Running Apache Benchmark test on /api/products"
          ab -n 10000 -c 100 -k http://localhost:8080/api/products

      - name: Create performance report
        run: |
          echo "## Performance Test Results" > performance_report.md
          echo "" >> performance_report.md
          echo "Test executed with 10000 requests and concurrency level of 100" >> performance_report.md
          echo "" >> performance_report.md
          echo "Full test results for /api/health:" >> performance_report.md
          echo '```' >> performance_report.md
          ab -n 10000 -c 100 -k http://localhost:8080/api/health >> performance_report.md
          echo '```' >> performance_report.md

      - name: Upload performance report
        uses: actions/upload-artifact@8a0c2d23819de87b9ed5e274e3b3fc68a3780714
        with:
          name: performance-report
          path: performance_report.md
